# Generated by Django 5.2.14 on 2026-05-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedfile',
            name='file',
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='content_type',
            field=models.CharField(default='application/octet-stream', max_length=100),
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='file_data',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='filename',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
    ]
